# Generated by Django 2.1 on 2019-02-20 02:02

import blanks.validators
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocEdited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_description', models.CharField(blank=True, max_length=250)),
                ('document_edited', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/grigor/pdf_3/private'), upload_to='documents_edited/')),
            ],
        ),
        migrations.CreateModel(
            name='DocFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_fields', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DocFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/', validators=[blanks.validators.validate_file_extension])),
            ],
        ),
    ]
